theme: jekyll-theme-minimal
title: Allan Registos' Porfolio Page
description: Bridging the gap between complex industrial data, scalable backend architectures, and high-availability server infrastructure.
